### ISSUE TITLE
Support for UICollectionView

### ISSUE THREAD

**Issue by kerrmarin** [diwu/DWURecyclingAlert#1]
Hi there,

It would be great to extend this component to support `UICollectionView`s and `UICollectionViewCell`s.

Thanks

**Comment by diwu** [comment]
Good point. I'll look into it and hopefully get back to you with a useful UICollectionViewCell update in one week or so.

**Comment by diwu** [comment]
Support for UICollectionView is now added into the master branch. Please give it a try and let me know if there's any problem.
