### ISSUE TITLE
It is not working with layer in UIView

### ISSUE THREAD

**Issue by macbaszii** [diwu/DWURecyclingAlert#2]
I try to use this but It cannot render the layer on UIView such as borderColor 

![screen shot 2558-06-19 at 11 48 40 pm](https://cloud.githubusercontent.com/assets/809559/8258261/bf5af132-16dd-11e5-8366-2c50f17a44dd.png)

following the figure
you will see my 3pt border color on bookmark button has not been rendered.

**Comment by diwu** [comment]
For now standalone CALayer instances are not supported. Yet it's definitely on my to-do list. Will work on it next week.

**Comment by diwu** [comment]
Support for CALayer detection is now added. Please download the latest code and re-test. Let me know if you still have problems.

**Comment by macbaszii** [comment]
Awesome, I will check it out :)
