### ISSUE TITLE
Support for UICollectionView headers and footers

### ISSUE THREAD

**Issue by graemesi** [diwu/DWURecyclingAlert#7]
UICollectionView headers and footers are created by using the [dequeueReusableSupplementaryViewOfKind:withReuseIdentifier:forIndexPath:] method. It would be a very useful addition if recycling alerts and timings were displayed for headers and footers.

**Comment by diwu** [comment]
Thanks @graemesi . Will think about a way to support headers and footers. Will get back to you shortly.

**Comment by graemesi** [comment]
Many thanks - I found DWURecyclingAlert very helpful for diagnosing some performance issues with cells in a complex collectionView. It's already a great tool, thank you for releasing it!

**Comment by diwu** [comment]
@graemesi Done. Give it a try.

**Comment by graemesi** [comment]
Thank you - it works great!
